export const CategoriaContrato = {
    'Empregado': 1,
    'Empregado Afastado para Prestar Serviço Militar Obrigatório': 3,
    'Empregado sob Contrato de Trabalho por Prazo Determinado (Lei n.9601/98)': 4,
    'Diretor não Empregado com FGTS (Lei n.8036/90, art.16)': 5,
    'Empregado Doméstico': 6,
    'Menor Aprendiz (Lei 10.097/2000)': 7,
    'Contribuinte Individual - Diretor não Empregado e demais Empresários sem FGTS': 11,
    'Demais Agentes Públicos': 12,
    'Contribuinte Individual - Trabalhador Autônomo ou a este equiparado, inclusive o operador de máquina, com Contribuição sobre a Remuneração': 13,
    'Contribuinte Individual - Cooperado que presta serviços a empresas contratantes da Cooperativa de Trabalho': 17,
    'Contribuinte Individual - Transportador Cooperado que presta serviços a empresas contratantes da Cooperativa de Trabalho': 18,
    'Agente Político': 19,
    'Servidor Público Ocupante, exclusivamente, de cargo em comissão': 20,
    'Servidor Público titular de cargo efetivo, magistrado, membro do Ministério Público': 21,
    'Contribuinte Individual cooperado que presta serviços à entidade beneficente isenta da cota patronal, por intermédio da coop. de trabalho': 24,
    'Contribuinte Individual transportador cooperado que presta serviços à entidade beneficente isenta cota patronal, por intermédio da coop trabalho': 25,
    'Dirigente sind., em relação adic. pago pelo sind. magistr. classista temp. Just. Trab. magistr. Trib. Eleit., 3 sit., mantida qualid. segur. empreg. (s/FGTS)': 26,
}