export const CategoriaESocial = {
    'Empregado Geral': 101,
    'Empregado Trabalhador Rural por Pequeno Prazo da Lei 11.718/2008': 102,
    'Empregado Aprendiz': 103,
    'Empregado Doméstico': 104,
    'Empregado contrato a termo firmado nos termos da Lei 9601/98': 105,
    'Empregado contrato por prazo determinado nos termos da Lei 6019/74': 106,
    'Trabalhador Avulso Portuário': 201,
    'Trabalhador Avulso Não Portuário': 202,
    'Servidor Público Titular de Cargo Efetivo': 301,
    'Servidor Público Ocupante de Cargo exclusivo em comissão': 302,
    'Agente Político': 303,
    'Servidor Público indicado para conselho ou órgão representativo': 305,
    'Servidor Público Contrato Temporário': 306,
    'Militar efetivo': 307,
    'Conscrito': 308,
    'Agente Público - Outros': 309,
    'Dirigente Sindical Informação prestada pelo Sindicato': 401,
    'Trabalhador Cedido Informação prestada pelo Cessionário': 410,
    'Contr. Ind. Autônomo em geral, exceto demais categorias de contribuinte individual': 701,
    'Contr. Ind. Transportador autônomo de passageiros': 711,
    'Contr. Ind. Transportador autônomo de carga': 711,
    'Contr. Ind. Diretor não empregado, com FGTS': 721,
    'Contr. Ind. Diretor não empregado, sem FGTS': 722,
    'Contr. Ind. empresários, sócios e membro de conselho de administração ou fiscal': 723,
    'Contr. Ind. Cooperado que presta serviços Cooperativa de Trabalho': 731,
    'Contr. Ind. Transportador Cooperado que presta serviços cooperativa de trabalho': 734,
    'Contr. Ind. Cooperado filiado a Cooperativa de Produção': 738,
    'Contr. Ind. MEI, quando contratado por PJ': 741,
    'Contr. Ind. - Aposentado magistrado classista temporário da Justiça do Trabalho ou da Justiça Eleitoral': 751,
    'Contr. Ind. Associado eleito para direção de Cooperativa,síndico ou administrador, remunerado': 761,
    'Contr. Ind. Membro de conselho tutelar, nos termos da Lei n� 8.069, de 13 de julho de 1990': 771,
    'Ministro de confissão religiosa ou membro de vida consagrada, de congregação ou de ordem religiosa': 781,
    'Estagiário': 901,
    'Médico Residente': 902,
    'Bolsista, nos termos da lei 8958/1994': 903,
}