export const GrauInstrucao = {
    'selecionar': 0,
    'Analfabeto': 1,
    'Até a 4º série incompleta do ensino fundamental': 2,
    'Com a 4º série completa do ensino fundamental': 3,
    'De 5 a 8º série incompleta do ensino fundamental': 4,
    'Ensino fundamental completo': 5,
    'Ensino médio incompleto': 6,
    'Ensino médio completo': 7,
    'Superior Incompleto': 8,
    'Superior Completo': 9,
    'Especialização': 10,
    'Mestrado': 11,
    'Doutorado': 12,
    'Pós Doutorado': 13,
}
