export const Nacionalidade = {
    'selecionar': 0,
    'Brasileiro': 10,
    'Brasileiro nascido no exterior': 15,
    'Naturalizado brasileiro': 20,
    'Argentino': 21,
    'Boliviano': 22,
    'Chileno': 23,
    'Paraguaio': 24,
    'Uruguaio': 25,
    'Venezuelano': 26,
    'Colombiano': 27,
    'Peruano': 28,
    'Equatoriano': 29,
    'Alemão': 30,
    'Belga': 31,
    'Britânico': 32,
    'Canadense': 34,
    'Espanhol': 35,
    'Norte-americano(EUA)': 36,
    'Francês': 37,
    'Suíço': 38,
    'Italiano': 39,
    'Haitiano': 40,
    'Japonês': 41,
    'Chinês': 42,
    'Coreano': 43,
    'Russo': 44,
    'Português': 45,
    'Paquistanês': 46,
    'Indiano': 47,
    'Outros latino-americanos': 48,
    'Outros asiáticos': 49,
    'Outros': 50,
    'Outros Europeus': 51,
    'Angolano': 60,
    'Congolês': 61,
    'Sul-Africano': 62,
    'Outros Africanos': 70,
}