export const Qualificacao = {
    'Diretor': 203,
    'Conselheiro de Administração': 204,
    'Administrador=205;Administrador de Grupo': 206,
    'Administrador de Sociedade Filiada': 207,
    'Administrador Judicial - Pessoa Física': 220,
    'Administrador Judicial - Pessoa Jurídica - Profissional Responsável': 222,
    'Administrador Judicial/Gestor': 223,
    'Gestor Judicial': 226,
    'Procurador': 309,
    'Inventariante': 312,
    'Liquidante': 313,
    'Interventor': 315,
    'Titular Pessoa Física': 401,
    'Empresário': 801,
    'Contador': 900,
    'Outros': 999,
}