public int CodigoContador { get; set; }
        public DateTime? DataInicial { get; set; }
        public string NomeContador { get; set; }
        public string CepEnderecoContador { get; set; }
        public string CodigoTipoLogradouro { get; set; }
        public string EnderecoContador { get; set; }
        public int NumeroEnderecoContador { get; set; }
        public string ComplementoEnderecoContador { get; set; }
        public string BairroContador { get; set; }
        public string SiglaEstado { get; set; }
        public int CodigoMunicipio { get; set; }
        public DateTime? DataAlteracaoEndereco { get; set; }
        public int DddFone { get; set; }
        public string NumeroFone { get; set; }
        public string Ramal { get; set; }
        public int DddFax { get; set; }
        public string DddCelular { get; set; }
        public string NumeroCelular { get; set; }
        public string NumeroFax { get; set; }
        public string TipoInscricaoFederal { get; set; }
        public string InscricalFederal { get; set; }
        public string CpfResponsavelCaepfContador { get; set; }
        public string TipoCaepfContador { get; set; }
        public string InscricaoCaepfContador { get; set; }
        public string NumeroRg { get; set; }
        public string OrgaoEmissorRg { get; set; }
        public string SiglaEstadoRg { get; set; }
        public DateTime? DataRg { get; set; }
        public bool TransferidoOuSecundario { get; set; }
        public string NumeroRegistroConselhoContador { get; set; }
        public string TituloProfissao { get; set; }
        public int Qualificacao { get; set; }
        public string EstadoExpedicaoConselhoContador { get; set; }
        public string NumeroSequenciaConselhoContador { get; set; }
        public DateTime? DataValidadeCrc { get; set; }
        public string UsuarioSat { get; set; }
        public string SenhaSat { get; set; }
        public string InscricaoMunicipalConselhoContador { get; set; }
        public string Email { get; set; }
        public DateTime? DataNascimento { get; set; }
        public string PaginaInternet { get; set; }
        public int TipoAlteracaoSocial { get; set; }