import { ITable } from '../data-interface'
  
const DataBusinessManager: ITable[] = [
    {
        titleName: 'Contador',
        tableName: 'contador',
        children: [
            {
                labelName: '',
                tableFieldName: 'Codigo',
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'CodigoEmpresa', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'CodigoSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DataInicial', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'NomeSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'TipoInscricaoFederalSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'InscricaoFederal', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'CepSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'CodigoLogradouro', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'EnderecoSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'NumeroEnderecoSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'ComplementoEnderecoSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'BairroEnderecoSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'SiglaEstadoPais', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'CodigoMunicipio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DddTelefoneSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'NumeroTelefone', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'NumeroRamalSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DddFax', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'NumeroFaxSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DddCelular', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'CelularSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'EmailSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'ResponsavelLegal', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'TipoSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'PerfilTarefa', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DescricaoCargo', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'QualificacaoSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'ValorNominalCotas', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'PercentualCotasSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'QuantidadeCotasDoCapital', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'ParticipacaoAssinaturaNosRelatorios', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'OrdemImpressaoAssinaturaSociosNosRelatorios', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DeclaracaoPessoaFisica', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'QualificacaoSocioIrpj', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'IndicadorSocioOstensivo', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DataEntradaSocioNaEmpresa', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DataSaidaSocioNaEmpresa', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'InscricaoInssSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'PisSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'NumeroRg', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'CodigoOrgaoEmissorRg', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'SiglaEstadoEmissorRg', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DataEmissaoRg', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'TituloEleitoralSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'ZonaTituloEleitoralSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'SecaoTituloEleitoralSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DataNascimento', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'SiglaEstadoNascimento', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'CodigoMunicipioNascimento', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'Nacionalidade', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'GrauInstrucaoDoSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'Formacao', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'EstadoCivil', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'RegimeCasamentoSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'IdadeSocio', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'NomeRepresentanteLegal', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'CpfRepresentanteLegal', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'QualificacaoRepresentanteLegal', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'NomeMae', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'InscricaoFederalMae', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DataNascimentoMae', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'NomePai', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'InscricaoFederalPai', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'DataNascimentoPai', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'TipoAlteracaoSocial', 
                typeImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                tableFieldName: 'StatusSincronizadoZen', 
                typeImput: '',
                numberOfCharacters: 0,
            },
        ]
    },
  ];