public int Codigo { get; set; }
public int CodigoEmpresa { get; set; }
public long? CodigoEstabelecimento { get; set; }
public string NomeEstabelecimento { get; set; }
public DateTime? DataInicial { get; set; }
public string NomeEstabelecimentoCompleto { get; set; }
public string NomeFantasiaFilial { get; set; }
public string ApelidoEstabelecimento { get; set; }
public string CepEnderecoEstabelecimento { get; set; }
public int? CodigoTipoLogradouro { get; set; }
public string EnderecoEstabelecimento { get; set; }
public int NumeroEnderecoEstabelecimento { get; set; }
public string ComplementoEnderecoEstabelecimento { get; set; }
public string BairroEnderecoEstabelecimento { get; set; }
public DateTime? DataUltimaAlteracaoEndereco { get; set; }
public string SiglaEstado { get; set; }
public int? CodigoMunicipio { get; set; }
public string DDDTelefone { get; set; }
public string NumeroTelefone { get; set; }
public string DDDFax { get; set; }
public string NumeroFax { get; set; }
public string CaixaPostal { get; set; }
public string SiglaEstadoCaixaPostal { get; set; }
public string CepCaixaPostal { get; set; }
public string Email { get; set; }
public string EmailDpo { get; set; }
public string PaginaInternet { get; set; }
public DateTime? DataInicioAtividade { get; set; }
public DateTime? DataEnceraAtividade { get; set; }
public bool SociedadeContaParticipacao { get; set; }
public string InscricaoScp { get; set; }
public string TipoInscricao { get; set; }
public string InscricaoFederal { get; set; }
public string CpfResponsavelCno { get; set; }
public string Caepf { get; set; }
public string InscricaoCaepf { get; set; }
public string InscricaoFederalProdutorRural { get; set; }
public string Suframa { get; set; }
public int CodigoNaturezaJuridica { get; set; }
public string CodigoAtividadeFederal { get; set; }
public string DescricaoAtividadeFederalEstabelecimento { get; set; }
public DateTime? DataAlteracaoAtividadeFederal { get; set; }
public int? TipoRegistro { get; set; }
public string NumeroRegistro { get; set; }
public DateTime? DataRegistro { get; set; }
public string ObservacaoRegistro { get; set; }
public string InscricaoEstadual { get; set; }
public string CodigoAtividadeEstadual { get; set; }
public string DescricaoAtividadeEstadualEstabelecimento { get; set; }
public string InscricaoMunicipal { get; set; }
public string CodigoAtividadeMunicipal { get; set; }
public string InscricaoMobiliaria { get; set; }
public string EspecieEstabelecimento { get; set; }
public string InscricaoBancoCentral { get; set; }
public string InscricaoSusep { get; set; }
public string DescricaoAtividadeMunicipalEstabelecimento { get; set; }
public string InscricaoCvm { get; set; }
public int CodigoTabelaFeriado { get; set; }
public double ValorNominalCotas { get; set; }
public string CapitalSocial { get; set; }
public int PorteEmpresa { get; set; }
public string NomeAuditor { get; set; }
public string CvmAuditor { get; set; }
public string InscricaoFederalAuditor { get; set; }
public string CodigoCategoriaEmpresaCliente { get; set; }
public int TipoAlteracaoESocial { get; set; }
public string Certificado { get; set; }
public int StatusSincZen { get; set; }
public DateTime? DataHistorico { get; set; }