import { ITable } from '../DataInterface'

import { DDD } from './../data-questor/DDD';
import { TipoPessoa } from './../data-questor/TipoPessoa';
import { EstadoCivil } from './../data-questor/EstadoCivil';
import { OrgaoEmissor } from './../data-questor/OrgaoEmissor';
import { PerfilTarefa } from './../data-questor/PerfilTarefa';
import { Qualificacao } from './../data-questor/Qualificacao';
import { GrauInstrucao } from './../data-questor/GrauInstrucao';
import { Nacionalidade } from './../data-questor/Nacionalidade';
import { TipoLogradouro } from './../data-questor/TipoLogradouro';
import { EstadoMunicipio } from './../data-questor/EstadoMunicipio';
import { MaiorMenorIdade, TipoInscricaoFederal } from '../data-questor/Options'
import { QualificacaoResponsavel } from './../data-questor/QualificacaoResponsavel';
  
export const DataSocio: ITable = 
    {
        titleName: 'Contador',
        tableName: 'contador',
        children: [
            {
                requiredField: true,
                labelName: 'Código da Empresa',
                placeholder: 'digite o código da empresa',
                tableFieldName: 'CodigoEmpresa', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 5,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Código do Sócio',
                placeholder: 'digite o código do sócio',
                tableFieldName: 'CodigoSocio', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 5,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Data Inicial',
                placeholder: 'ex: 01/01/1900',
                tableFieldName: 'DataInicial', 
                typeImput: 'date',
                typeDataImputReturn: 'string',
                numberOfCharacters: 10,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Nome',
                placeholder: 'digite o nome do socio',
                tableFieldName: 'NomeSocio', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                numberOfCharacters: 50,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Tipo de Inscrição Federal',
                placeholder: 'Informe se Cpf ou Cnpj',
                tableFieldName: 'TipoInscricaoFederalSocio', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: TipoInscricaoFederal,
                numberOfCharacters: 2,
                fixedValue: null,
                children: [
                    {
                        requiredField: true,
                        labelName: 'Cadastro: de Pessoa Física / Nacional de Pessoa Jurídica',
                        placeholder: 'XXX.XXX.XXX-XX ou XX.XXX.XXX/0001-XX',
                        tableFieldName: 'InscricaoFederal', 
                        typeImput: 'text',
                        typeDataImputReturn: 'string',
                        mask: ['000.000.000-00', '00.000.000/0001-00'],
                        numberOfCharacters: 18,
                        fixedValue: null,
                    },
                ]
            },
            {
                requiredField: true,
                labelName: 'CEP',
                placeholder: 'informe o cep do socio',
                tableFieldName: 'CepSocio', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                mask: ['00.000-000'],
                numberOfCharacters: 10,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Tipo de Logradouro',
                placeholder: 'informe se é rua, avenida, etc.',
                tableFieldName: 'CodigoLogradouro', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: TipoLogradouro,
                numberOfCharacters: 21,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Endereço',
                placeholder: 'digite o nome da rua',
                tableFieldName: 'EnderecoSocio', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                numberOfCharacters: 40,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Número',
                placeholder: 'digite o número do endereço',
                tableFieldName: 'NumeroEnderecoSocio', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 7,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Complemento',
                placeholder: 'exemplo: casa, apto, bloco...',
                tableFieldName: 'ComplementoEnderecoSocio', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                numberOfCharacters: 20,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Bairro',
                placeholder: 'digite o nome de seu bairro',
                tableFieldName: 'BairroEnderecoSocio', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                numberOfCharacters: 30,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Estado',
                placeholder: 'informe a sigla do estado',
                tableFieldName: 'SiglaEstadoPais', 
                typeImput: 'select',
                typeDataImputReturn: 'string',
                optionsImput: EstadoMunicipio,
                numberOfCharacters: 2,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Município',
                placeholder: 'informe o município',
                tableFieldName: 'CodigoMunicipio', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 8,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'DDD Telefone',
                placeholder: 'digite o DDD',
                tableFieldName: 'DddTelefoneSocio', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: DDD,
                numberOfCharacters: 5,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Telefone',
                placeholder: 'digite o número de telefone',
                tableFieldName: 'NumeroTelefone', 
                typeImput: 'phone',
                typeDataImputReturn: 'integer',
                mask: ['00000-0000'],
                numberOfCharacters: 10,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'Ramal',
                placeholder: 'digite o Ramal',
                tableFieldName: 'NumeroRamalSocio', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 5,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'DDD Fax',
                placeholder: 'digite o DDD',
                tableFieldName: 'DddFax', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: DDD,
                numberOfCharacters: 5,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'Fax',
                placeholder: 'digite o número do ramal',
                tableFieldName: 'NumeroFaxSocio', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                mask: ['00000-0000'],
                numberOfCharacters: 10,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'DDD Celular',
                placeholder: 'digite o DDD',
                tableFieldName: 'DddCelular', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: DDD,
                numberOfCharacters: 5,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'Celular',
                placeholder: 'informe o celular do socio',
                tableFieldName: 'CelularSocio', 
                typeImput: 'phone',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 10,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'E-mail',
                placeholder: 'Digite seu e-mail',
                tableFieldName: 'EmailSocio', 
                typeImput: 'email',
                typeDataImputReturn: 'string',
                numberOfCharacters: 100,
                fixedValue: null,
            },
            {
                requiredField: false,
                tableFieldName: 'ResponsavelLegal', 
                typeDataImputReturn: 'integer',
                numberOfCharacters: 1,
                fixedValue: 1,
            },
            {
                requiredField: true,
                labelName: 'Tipo da pessoa',
                placeholder: 'Informe o tipo da pessoa',
                tableFieldName: 'TipoSocio',
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: TipoPessoa,
                numberOfCharacters: 1,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Perfil tarefa',
                placeholder: 'Informe o perfil tarefa',
                tableFieldName: 'PerfilTarefa', 
                typeImput: 'select',
                typeDataImputReturn: 'string',
                optionsImput: PerfilTarefa,
                numberOfCharacters: 20,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Descrição do cargo',
                placeholder: 'informe a descrição do cargo',
                tableFieldName: 'DescricaoCargo', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                numberOfCharacters: 50,
                fixedValue: null,
            },
            {
                requiredField: false,
                tableFieldName: 'QualificacaoSocio', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: Qualificacao,
                numberOfCharacters: 5,
                fixedValue: 203,
            },
            {
                requiredField: false,
                tableFieldName: 'ValorNominalCotas', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 16,
                fixedValue: 0,
            },
            {
                requiredField: true,
                labelName: 'Percentual de cotas',
                placeholder: 'informe o percentual de cotas do sócio',
                tableFieldName: 'PercentualCotasSocio', 
                typeImput: 'moeda',
                typeDataImputReturn: 'float',
                numberOfCharacters: 9,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Quantidade de quotas do capital',
                placeholder: 'informe a quantidade de quotas',
                tableFieldName: 'QuantidadeCotasDoCapital', 
                typeImput: 'moeda',
                typeDataImputReturn: 'float',
                numberOfCharacters: 16,
                fixedValue: null,
            },
            {
                requiredField: false,
                tableFieldName: 'ParticipacaoAssinaturaNosRelatorios', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 1,
                fixedValue: 1,
            },
            {
                requiredField: true,
                labelName: 'Ordem de impressão da assinatura nos relatórios',
                tableFieldName: 'OrdemImpressaoAssinaturaSociosNosRelatorios', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 5,
                fixedValue: null,
            },
            {
                requiredField: false,
                tableFieldName: 'DeclaracaoPessoaFisica', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 1,
                fixedValue: 0,
            },
            {
                requiredField: false,
                tableFieldName: 'QualificacaoSocioIrpj', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 5,
                fixedValue: 2,
            },
            {
                requiredField: false,
                tableFieldName: 'IndicadorSocioOstensivo', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 1,
                fixedValue: 0,
            },
            {
                requiredField: true,
                labelName: 'Entrada na Empresa',
                placeholder: 'informe a data de entrada do sócio na empresa',
                tableFieldName: 'DataEntradaSocioNaEmpresa', 
                typeImput: 'date',
                typeDataImputReturn: 'string',
                numberOfCharacters: 10,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'Saída da empresa',
                placeholder: 'Informe a data saída do sócio na empresa',
                tableFieldName: 'DataSaidaSocioNaEmpresa', 
                typeImput: 'date',
                typeDataImputReturn: 'string',
                numberOfCharacters: 10,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Inscrição no INSS',
                placeholder: 'informe o número da inscrição no INSS do sócio ',
                tableFieldName: 'InscricaoInssSocio', 
                typeImput: 'number',
                typeDataImputReturn: 'string',
                numberOfCharacters: 14,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'PIS do sócio',
                placeholder: 'informe o número do PIS do sócio',
                tableFieldName: 'PisSocio', 
                typeImput: 'number',
                typeDataImputReturn: 'string',
                numberOfCharacters: 14,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'RG',
                placeholder: 'informe o número do registro geral do sócio ',
                tableFieldName: 'NumeroRg', 
                typeImput: 'number',
                typeDataImputReturn: 'string',
                numberOfCharacters: 20,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Orgão Emissor RG',
                placeholder: 'informe o órgão emissor do registro geral do sócio',
                tableFieldName: 'CodigoOrgaoEmissorRg', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: OrgaoEmissor,
                numberOfCharacters: 21,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Estado Órgão Emissor RG',
                placeholder: 'informe a sigla do estado emissor do registro geral',
                tableFieldName: 'SiglaEstadoEmissorRg', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                optionsImput: EstadoMunicipio,
                numberOfCharacters: 2,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Data de Emissão do RG',
                placeholder: 'informe a data de emissão do RG',
                tableFieldName: 'DataEmissaoRg', 
                typeImput: 'date',
                typeDataImputReturn: 'string',
                numberOfCharacters: 10,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'Título Eleitoral',
                placeholder: 'informe o número do título eleitoral do sócio',
                tableFieldName: 'TituloEleitoralSocio', 
                typeImput: 'number',
                typeDataImputReturn: 'string',
                numberOfCharacters: 13,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'Zona do Título Eleitoral',
                placeholder: 'informe a zona do título eleitoral do sócio',
                tableFieldName: 'ZonaTituloEleitoralSocio', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 5,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'Seção do Título Eleitoral',
                placeholder: 'informe a seção do título eleitoral do sócio',
                tableFieldName: 'SecaoTituloEleitoralSocio', 
                typeImput: 'number',
                typeDataImputReturn: 'integer',
                numberOfCharacters: 5,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Data de Nascimento',
                placeholder: 'informe a data de nascimento',
                tableFieldName: 'DataNascimento', 
                typeImput: 'date',
                typeDataImputReturn: 'string',
                numberOfCharacters: 10,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Estado de Nascimento',
                placeholder: 'informe a sigla do estado de nascimento',
                tableFieldName: 'SiglaEstadoNascimento', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                optionsImput: EstadoMunicipio,
                numberOfCharacters: 2,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Município de Nascimento',
                placeholder: 'informe o município de nascimento',
                tableFieldName: 'CodigoMunicipioNascimento', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: EstadoMunicipio,
                numberOfCharacters: 8,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Nacionalidade',
                placeholder: 'informe a nacionalidade',
                tableFieldName: 'Nacionalidade', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: Nacionalidade,
                numberOfCharacters: 3,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Grau de instrução',
                placeholder: 'informe o grau de instrução do sócio',
                tableFieldName: 'GrauInstrucaoDoSocio', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: GrauInstrucao,
                numberOfCharacters: 3,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'Formação técnica',
                placeholder: 'informe a formação técnica do sócio. Ex.: Empresário, Analista de Sistemas, Engenheiro, etc',
                tableFieldName: 'Formacao', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                numberOfCharacters: 50,
                fixedValue: null,
            },
            {
                requiredField: true,
                labelName: 'Estado Civil',
                placeholder: 'informe o estado civil',
                tableFieldName: 'EstadoCivil', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: EstadoCivil,
                numberOfCharacters: 2,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'Regime de casamento',
                placeholder: 'informe o regime de casamento do sócio',
                tableFieldName: 'RegimeCasamentoSocio', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                numberOfCharacters: 50,
                fixedValue: null,
            },
            {
                requiredField: false,
                labelName: 'Maior de 18 anos?',
                placeholder: 'informe a idade do socio',
                tableFieldName: 'IdadeSocio', 
                typeImput: 'select',
                typeDataImputReturn: 'integer',
                optionsImput: MaiorMenorIdade,
                numberOfCharacters: 2,
                fixedValue: null,
                children: [
                    {
                        requiredField: true,
                        labelName: 'Representante legal',
                        placeholder: 'informe o nome do representante legal quando o sócio for menor',
                        tableFieldName: 'NomeRepresentanteLegal', 
                        typeImput: 'text',
                        typeDataImputReturn: 'string',
                        numberOfCharacters: 50,
                        fixedValue: null,
                    },
                    {
                        requiredField: true,
                        labelName: 'CPF do Representante',
                        placeholder: 'informe o cpf do representante legal',
                        tableFieldName: 'CpfRepresentanteLegal', 
                        typeImput: 'text',
                        typeDataImputReturn: 'string',
                        mask: ['000.000.000-00'],
                        numberOfCharacters: 14,
                        fixedValue: null,
                    },
                    {
                        requiredField: true,
                        labelName: 'Qualificação do Representante',
                        placeholder: 'Informe a qualificação do representante legal',
                        tableFieldName: 'QualificacaoRepresentanteLegal', 
                        typeImput: 'select',
                        typeDataImputReturn: 'integer',
                        optionsImput: QualificacaoResponsavel,
                        numberOfCharacters: 5,
                        fixedValue: null,
                    },
                ]
            },
            {
                requiredField: true,
                labelName: 'Nome da Mãe',
                placeholder: 'informe o nome da mãe',
                tableFieldName: 'NomeMae', 
                typeImput: 'text',
                typeDataImputReturn: 'string',
                numberOfCharacters: 50,
                fixedValue: null,
                children: [
                    {
                        requiredField: true,
                        labelName: 'Cadastro: de Pessoa Física / Nacional de Pessoa Jurídica',
                        placeholder: 'informe a inscrição federal da mãe',
                        tableFieldName: 'InscricaoFederalMae', 
                        typeImput: 'text',
                        typeDataImputReturn: 'string',
                        mask: ['000.000.000-00', '00.000.000/0001-00'],
                        numberOfCharacters: 18,
                        fixedValue: null,
                    },
                    {
                        requiredField: true,
                        labelName: 'Data de Nascimento',
                        placeholder: 'informe a data de nascimento da mãe',
                        tableFieldName: 'DataNascimentoMae', 
                        typeImput: 'date',
                        typeDataImputReturn: 'string',
                        numberOfCharacters: 10,
                        fixedValue: null,
                    },
                ]
            },
            {
                requiredField: true,
                labelName: 'Nome do Pai',
                placeholder: 'informe o nome do pai',
                tableFieldName: 'NomePai',
                typeImput: 'text',
                typeDataImputReturn: 'string',
                numberOfCharacters: 50,
                fixedValue: null,
                children: [
                    {
                        requiredField: true,
                        labelName: 'Cadastro: de Pessoa Física / Nacional de Pessoa Jurídica',
                        placeholder: 'informe a inscrição federal do pai',
                        tableFieldName: 'InscricaoFederalPai', 
                        typeImput: 'text',
                        typeDataImputReturn: 'string',
                        mask: ['000.000.000-00', '00.000.000/0001-00'],
                        numberOfCharacters: 18,
                        fixedValue: null,
                    },
                    {
                        requiredField: true,
                        labelName: 'Data de Nascimento',
                        placeholder: 'informe a data de nascimento do pai',
                        tableFieldName: 'DataNascimentoPai', 
                        typeImput: 'date',
                        typeDataImputReturn: 'string',
                        numberOfCharacters: 10,
                        fixedValue: null,
                    },
                ]
            },
            {
                requiredField: false,
                tableFieldName: 'TipoAlteracaoSocial', 
                typeDataImputReturn: 'integer',
                numberOfCharacters: 3,
                fixedValue: 0,
            },
            {
                requiredField: false,
                tableFieldName: 'StatusSincronizadoZen', 
                typeDataImputReturn: 'integer',
                numberOfCharacters: 5,
                fixedValue: 0,
            },
        ]
    }
  