import { ITable } from '../data-interface'
import { TipoLogradouro, TipoInscricaoFederal, DDD, SimNão, TipoPessoa, PerfilTarefa } from './../data-questor/from-to'
  
const DataSocio: ITable[] = [
    {
        titleName: 'Contador',
        tableName: 'contador',
        children: [
            {
                required: true,
                labelName: 'Código da Empresa',
                placeholder: 'digite o código da empresa',
                tableFieldName: 'CodigoEmpresa', 
                typeImput: 'number',
                typeDataImput: 'integer',
                numberOfCharacters: 5,
            },
            {
                required: true,
                labelName: 'Código do Sócio',
                placeholder: 'digite o código do sócio',
                tableFieldName: 'CodigoSocio', 
                typeImput: 'number',
                typeDataImput: 'integer',
                numberOfCharacters: 5,
            },
            {
                required: true,
                labelName: 'Data Inicial',
                placeholder: 'ex: 01/01/1900',
                tableFieldName: 'DataInicial', 
                typeImput: 'date',
                typeDataImput: 'string',
                mask: ['00/00/0000'],
                numberOfCharacters: 10,
            },
            {
                required: true,
                labelName: 'Nome',
                placeholder: 'digite o nome do socio',
                tableFieldName: 'NomeSocio', 
                typeImput: 'text',
                typeDataImput: 'string',
                numberOfCharacters: 50,
            },
            {
                required: true,
                labelName: 'Tipo de Inscrição Federal',
                placeholder: 'Informe se Cpf ou Cnpj',
                tableFieldName: 'TipoInscricaoFederalSocio', 
                typeImput: 'select',
                typeDataImput: 'integer',
                optionsImput: TipoInscricaoFederal,
                numberOfCharacters: 2,
            },
            {
                required: true,
                labelName: 'Cadastro: de Pessoa Física / Nacional de Pessoa Jurídica',
                placeholder: 'XXX.XXX.XXX-XX ou XX.XXX.XXX/0001-XX',
                tableFieldName: 'InscricaoFederal', 
                typeImput: 'text',
                typeDataImput: 'string',
                mask: ['000.000.000-00', '00.000.000/0001-00'],
                numberOfCharacters: 18,
            },
            {
                required: true,
                labelName: 'CEP',
                placeholder: 'XX.XXX-XXX',
                tableFieldName: 'CepSocio', 
                typeImput: 'text',
                typeDataImput: 'string',
                mask: ['00.000-000'],
                numberOfCharacters: 10,
            },
            {
                required: true,
                labelName: 'Tipo de Logradouro',
                placeholder: 'informe se é rua, avenida, etc.',
                tableFieldName: 'CodigoLogradouro', 
                typeImput: 'select',
                typeDataImput: 'integer',
                optionsImput: TipoLogradouro,
                numberOfCharacters: 21,
            },
            {
                required: true,
                labelName: 'Endereço',
                placeholder: 'digite o nome da rua',
                tableFieldName: 'EnderecoSocio', 
                typeImput: 'text',
                typeDataImput: 'string',
                numberOfCharacters: 40,
            },
            {
                required: true,
                labelName: 'Número',
                placeholder: 'digite o número do endereço',
                tableFieldName: 'NumeroEnderecoSocio', 
                typeImput: 'number',
                typeDataImput: 'integer',
                numberOfCharacters: 7,
            },
            {
                required: true,
                labelName: 'Complemento',
                placeholder: 'exemplo: casa, apto, bloco...',
                tableFieldName: 'ComplementoEnderecoSocio', 
                typeImput: 'text',
                typeDataImput: 'string',
                numberOfCharacters: 20,
            },
            {
                required: true,
                labelName: 'Bairro',
                placeholder: 'digite o nome de seu bairro',
                tableFieldName: 'BairroEnderecoSocio', 
                typeImput: 'text',
                typeDataImput: 'string',
                numberOfCharacters: 30,
            },
            {
                required: true,
                labelName: 'Estado',
                placeholder: 'informe a sigla do estado',
                tableFieldName: 'SiglaEstadoPais', 
                typeImput: 'select',
                typeDataImput: 'string',
                numberOfCharacters: 2,
            },
            {
                required: true,
                labelName: 'Município',
                placeholder: 'informe o município',
                tableFieldName: 'CodigoMunicipio', 
                typeImput: 'select',
                typeDataImput: 'integer',
                numberOfCharacters: 8,
            },
            {
                required: true,
                labelName: 'DDD Telefone',
                placeholder: 'digite o DDD',
                tableFieldName: 'DddTelefoneSocio', 
                typeImput: 'select',
                typeDataImput: 'integer',
                optionsImput: DDD,
                numberOfCharacters: 5,
            },
            {
                required: true,
                labelName: 'Telefone',
                placeholder: 'digite o número de telefone',
                tableFieldName: 'NumeroTelefone', 
                typeImput: 'number',
                typeDataImput: 'integer',
                mask: ['00000-0000'],
                numberOfCharacters: 10,
            },
            {
                required: true,
                labelName: 'Ramal',
                placeholder: 'digite o Ramal',
                tableFieldName: 'NumeroRamalSocio', 
                typeImput: 'number',
                typeDataImput: 'integer',
                numberOfCharacters: 5,
            },
            {
                required: true,
                labelName: 'DDD Fax',
                placeholder: 'digite o DDD',
                tableFieldName: 'DddFax', 
                typeImput: 'select',
                typeDataImput: 'integer',
                optionsImput: DDD,
                numberOfCharacters: 5,
            },
            {
                required: true,
                labelName: 'Fax',
                placeholder: 'digite o número do ramal',
                tableFieldName: 'NumeroFaxSocio', 
                typeImput: 'number',
                typeDataImput: 'integer',
                mask: ['00000-0000'],
                numberOfCharacters: 10,
            },
            {
                required: true,
                labelName: 'DDD Celular',
                placeholder: 'digite o DDD',
                tableFieldName: 'DddCelular', 
                typeImput: 'select',
                typeDataImput: 'integer',
                optionsImput: DDD,
                numberOfCharacters: 5,
            },
            {
                required: true,
                labelName: 'Celular',
                placeholder: '',
                tableFieldName: 'CelularSocio', 
                typeImput: 'number',
                typeDataImput: 'integer',
                mask: ['00000-0000'],
                numberOfCharacters: 10,
            },
            {
                required: true,
                labelName: 'E-mail',
                placeholder: 'Digite seu e-mail',
                tableFieldName: 'EmailSocio', 
                typeImput: 'text',
                typeDataImput: 'string',
                mask: ['email@email'],
                numberOfCharacters: 100,
            },
            {
                required: true,
                labelName: 'É reponsável legal?',
                placeholder: 'Sim / Não',
                tableFieldName: 'ResponsavelLegal', 
                typeImput: 'select',
                typeDataImput: 'integer',
                optionsImput: SimNão,
                numberOfCharacters: 1,
            },
            {
                required: true,
                labelName: 'Tipo da pessoa',
                placeholder: 'Informe o tipo da pessoa',
                tableFieldName: 'TipoSocio',
                typeImput: 'select',
                typeDataImput: 'integer',
                optionsImput: TipoPessoa,
                numberOfCharacters: 1,
            },
            {
                required: true,
                labelName: 'Perfil tarefa',
                placeholder: 'Informe o perfil tarefa',
                tableFieldName: 'PerfilTarefa', 
                typeImput: 'select',
                typeDataImput: 'string',
                optionsImput: PerfilTarefa,
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: 'Descrição do cargo',
                placeholder: 'informe a descrição do cargo',
                tableFieldName: 'DescricaoCargo', 
                typeImput: 'text',
                typeDataImput: 'string',
                numberOfCharacters: 50,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'QualificacaoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'ValorNominalCotas', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'PercentualCotasSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'QuantidadeCotasDoCapital', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'ParticipacaoAssinaturaNosRelatorios', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'OrdemImpressaoAssinaturaSociosNosRelatorios', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'DeclaracaoPessoaFisica', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'QualificacaoSocioIrpj', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'IndicadorSocioOstensivo', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataEntradaSocioNaEmpresa', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataSaidaSocioNaEmpresa', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'InscricaoInssSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'PisSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'NumeroRg', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'CodigoOrgaoEmissorRg', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'SiglaEstadoEmissorRg', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataEmissaoRg', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'TituloEleitoralSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'ZonaTituloEleitoralSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'SecaoTituloEleitoralSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataNascimento', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'SiglaEstadoNascimento', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'CodigoMunicipioNascimento', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'Nacionalidade', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'GrauInstrucaoDoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'Formacao', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'EstadoCivil', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'RegimeCasamentoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'IdadeSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'NomeRepresentanteLegal', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'CpfRepresentanteLegal', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'QualificacaoRepresentanteLegal', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'NomeMae', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'InscricaoFederalMae', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataNascimentoMae', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'NomePai', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'InscricaoFederalPai', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataNascimentoPai', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'TipoAlteracaoSocial', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                required: true,
                labelName: '',
                placeholder: '',
                tableFieldName: 'StatusSincronizadoZen', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
        ]
    },
  ];