import { ITable } from '../data-interface'
import { TipoLogradouro, TipoInscricaoFederal } from '../data-questor/from-to'
  
const DataSocio: ITable[] = [
    {
        titleName: 'Contador',
        tableName: 'contador',
        children: [
            {
                labelName: 'Código da Empresa',
                placeholder: '0',
                tableFieldName: 'CodigoEmpresa', 
                typeImput: 'number',
                typeDataImput: 'integer',
                numberOfCharacters: 5,
            },
            {
                labelName: 'Código do Sócio',
                placeholder: '0',
                tableFieldName: 'CodigoSocio', 
                typeImput: 'number',
                typeDataImput: 'integer',
                numberOfCharacters: 5,
            },
            {
                labelName: 'Data Inicial',
                placeholder: '01/01/1900',
                tableFieldName: 'DataInicial', 
                typeImput: 'date',
                typeDataImput: 'string',
                numberOfCharacters: 10,
            },
            {
                labelName: 'Nome',
                placeholder: 'nome do socio',
                tableFieldName: 'NomeSocio', 
                typeImput: 'text',
                typeDataImput: 'string',
                numberOfCharacters: 50,
            },
            {
                labelName: 'Tipo de Inscrição Federal',
                placeholder: 'CPF / CNPJ',
                tableFieldName: 'TipoInscricaoFederalSocio', 
                typeImput: 'select',
                typeDataImput: 'integer',
                optionsImput: TipoInscricaoFederal,
                numberOfCharacters: 2,
            },
            {
                labelName: 'Cadastro: de Pessoa Física / Nacional de Pessoa Jurídica',
                placeholder: 'XXX.XXX.XXX-XX ou XX.XXX.XXX/0001-XX',
                tableFieldName: 'InscricaoFederal', 
                typeImput: 'text',
                typeDataImput: 'string',
                numberOfCharacters: 18,
            },
            {
                labelName: 'CEP',
                placeholder: 'XX.XXX-XXX',
                tableFieldName: 'CepSocio', 
                typeImput: 'text',
                typeDataImput: 'string',
                numberOfCharacters: 10,
            },
            {
                labelName: 'Tipo de Logradouro',
                placeholder: 'rua, avenida...',
                tableFieldName: 'CodigoLogradouro', 
                typeImput: 'select',
                typeDataImput: 'integer',
                optionsImput: TipoLogradouro,
                numberOfCharacters: 21,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'EnderecoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'NumeroEnderecoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'ComplementoEnderecoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'BairroEnderecoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'SiglaEstadoPais', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'CodigoMunicipio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DddTelefoneSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'NumeroTelefone', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'NumeroRamalSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DddFax', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'NumeroFaxSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DddCelular', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'CelularSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'EmailSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'ResponsavelLegal', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'TipoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'PerfilTarefa', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DescricaoCargo', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'QualificacaoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'ValorNominalCotas', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'PercentualCotasSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'QuantidadeCotasDoCapital', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'ParticipacaoAssinaturaNosRelatorios', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'OrdemImpressaoAssinaturaSociosNosRelatorios', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DeclaracaoPessoaFisica', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'QualificacaoSocioIrpj', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'IndicadorSocioOstensivo', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataEntradaSocioNaEmpresa', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataSaidaSocioNaEmpresa', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'InscricaoInssSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'PisSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'NumeroRg', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'CodigoOrgaoEmissorRg', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'SiglaEstadoEmissorRg', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataEmissaoRg', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'TituloEleitoralSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'ZonaTituloEleitoralSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'SecaoTituloEleitoralSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataNascimento', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'SiglaEstadoNascimento', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'CodigoMunicipioNascimento', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'Nacionalidade', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'GrauInstrucaoDoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'Formacao', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'EstadoCivil', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'RegimeCasamentoSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'IdadeSocio', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'NomeRepresentanteLegal', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'CpfRepresentanteLegal', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'QualificacaoRepresentanteLegal', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'NomeMae', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'InscricaoFederalMae', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataNascimentoMae', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'NomePai', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'InscricaoFederalPai', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'DataNascimentoPai', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'TipoAlteracaoSocial', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
            {
                labelName: '',
                placeholder: '',
                tableFieldName: 'StatusSincronizadoZen', 
                typeImput: '',
                typeDataImput: '',
                numberOfCharacters: 0,
            },
        ]
    },
  ];